# Permalinks
permalink:           pretty


# Site settings
title:                map and pipe operator # the title of our blog
tagline:              Asako Mikami
description:          'The title is attributed to two of my favorite R functions.'
baseurl:              "" # we won't need to set that in our case
url:                  https://amikami102.github.io # set it like this for now but we'll have to change this before to send it live
github_username:      amikami102 # your github username (if you have one)

# Build settings
markdown: kramdown
paginate: 3 # number of posts you want per page

# About/contact
author:
  name:              Asako Mikami
  url:               https://github.com/amikami102
  email:             afmikami@bu.edu

# Custom vars
version:             1.0.0

plugins: 
  - jekyll-paginate