# Permalinks
permalink:           pretty

# Setup
title:               'map(planA, ~ get_planB(.))'
tagline:             'Asako Mikami'
description:         'I write this blog to keep myself accountable.'
url:                 https://amikami102.github.io
baseurl:             /
paginate:            3

# About/contact
author:
  name:              Asako Mikami
  url:               https://github.com/amikami102
  email:             asakomikami@gmail.com

# Custom vars
version:             1.0.0
