# Permalinks
permalink:           pretty

# Setup
title:               'map and pipe operator'
tagline:             'Asako Mikami'
description:         'I write this blog to keep myself accountable. The title is attributed to my favorite `R` functions.'
url:                  ''
baseurl:             /
paginate:            3

# About/contact
author:
  name:              Asako Mikami
  url:               https://github.com/amikami102
  email:             asakomikami@gmail.com

# Custom vars
version:             1.0.0

plugins: [jekyll-paginate]